version: "3.9" #La version de Docker Compose que hemos  utilitzado (en este caso es la version 3.9)
services:
  # OPENLDAP (OK)
  openldap:
    image: osixia/openldap:latest  # Hemos utilitzado la imagen osixia/openldap más reciente    
    container_name: openldap      # Hemos configurado el nombre del contenedor y el nombre de host como 'openldap'    
    hostname: openldap
    ports:  # Hemos definido el puerto 636 del contenedor al puerto 636 del host para la comunicación TLS
      - "636:636"
    volumes:  # Hemos montado volúmenes para almacenar datos. 
      - './certificados:/container/service/slapd/assets/certs:rw' #certificados
      - './LDAP/slapd/database:/var/lib/ldap:rw'  # base de datos
      - './LDAP/slapd/config:/etc/ldap/slapd.d:rw'  #configuración de LDAP
      # Configuracion de las variables de entorno para OpenLDAP
    environment:
      - LDAP_ORGANISATION=hotelmoro
      - LDAP_DOMAIN=hotelmoro.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_CONFIG_PASSWORD=admin123
      - LDAP_BASE_DN=dc=hotelmoro,dc=com
      - LDAP_TLS_CRT_FILENAME=hotelmoro.crt
      - LDAP_TLS_KEY_FILENAME=hotelmoro.key
      - LDAP_TLS_CA_CRT_FILENAME=hotelmoro.com.ca.crt
      - LDAP_READONLY_USER=false
    networks:
      - redhotelmoro # conexion a la red especificada (redhotelmoro)

  # Phpldap (OK)
  phpldapadmin: #especificamos el nombre del servicio
    image: osixia/phpldapadmin:latest #indicamos el nombre de la imagen del contenedor más reciente (con la etiqueta latest)
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "100:80"

    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - redhotelmoro

  #CoreDNS (OK)
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    ports:
      - "54:54/udp"
    volumes:
      - './Corefile:/etc/coredns/Corefile:rw'
    environment:
      - COREDNS_ALLOW_UPDATE=yes
      - COREDNS_ALLOW_AXFR_IPS=0.0.0.0/0
      - COREDNS_IP=192.168.1.100
    networks:
      - redhotelmoro


  # PHP-Apache  (OK)
  PHP-Apache:
    image: php:apache
    container_name: PHP-Apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html:rw
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - redhotelmoro



  # MySQL  (OK)
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: HotelMoro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:rw
    networks:
      - redhotelmoro

  # PHPMyAdmin (OK)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "90:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - './mysql:/containerPath:ro'
    networks:
      - redhotelmoro

  #Postfix
  mailserver:
    image: analogic/poste.io
    container_name: Postfix
    restart: always
    expose:
      - "25"
    environment:
      - TZ=Europe/Barcelona
      - h=mail.hotelmoro.com # Direccion del servidor de mail hosting
      - HTTP_PORT=8080
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE
      - DNS_SERVER=192.168.1.100
    volumes:
      - './mnt/mail:/data:rw'
    networks:
      - redhotelmoro




  #Dovecot
  dovecot:
    image: dovecot/dovecot
    container_name: dovecot
    volumes:
      - './certificados:/etc/ssl/private:rw'
    networks:
      - redhotelmoro




  # Portainer (Administrador de Servicios)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=administrador
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - redhotelmoro

networks:
  redhotelmoro:
    driver: bridge

volumes:
  openldap-data:
  ftp-data:
  ftp-log-data:
  sftp-data:
  portainer_data:
