version: "3.9" #La version de Docker Compose que hemos  utilitzado (en este caso es la version 3.9)
services:
  # OPENLDAP (OK)
  openldap:
    image: osixia/openldap:latest  # Hemos utilitzado la imagen osixia/openldap más reciente    
    container_name: openldap      # Hemos configurado el nombre del contenedor y el nombre de host como 'openldap'    
    hostname: openldap
    ports:  # Hemos definido el puerto 636 del contenedor al puerto 636 del host para la comunicación TLS
      - "636:636"
    # Configuracion de las variables de entorno para OpenLDAP
    environment:
      - LDAP_ORGANISATION=elindio
      - LDAP_DOMAIN=elindio.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_CONFIG_PASSWORD=admin123
      - LDAP_BASE_DN=dc=elindio,dc=com
      - LDAP_TLS_CRT_FILENAME=elindio.crt
      - LDAP_TLS_KEY_FILENAME=elindio.key
      - LDAP_TLS_CA_CRT_FILENAME=elindio.com.ca.crt
      - LDAP_READONLY_USER=false
    networks:
      - redelindio # conexion a la red especificada (redelindio)

  # Phpldap (OK)
  phpldapadmin: #especificamos el nombre del servicio
    image: osixia/phpldapadmin:latest #indicamos el nombre de la imagen del contenedor más reciente (con la etiqueta latest)
    container_name: phpldapadmin #Definimos el nombre del contenedor como phpldapadmin
    hostname: phpldapadmin #Asignamos el nombre del host del contendor como phpldapadmin
    ports:
      - "100:80" # Se establece una conexion entre el puerto 100 del host y el puerto 80.
    # Configuración de las variables de enotrno
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # Configura el host LDAP al que PHP LDAP Admin se conectarà
      - PHPLDAPADMIN_HTTPS=false # Se deshabilita HTTPS para PHP LDAP Admin
      - PHPLDAPADMIN_LDAP_ADMIN_USERNAME=admin
      - PHPLDAPADMIN_LDAP_ADMIN_PASSWORD=admin123
    depends_on:
      - openldap # define que este servicio depende del servicio openldap
    networks:
      - redelindio # Asignamos el contenedor a la red "redelindio"


  # PHP-Apache  (OK)
  PHP-Apache:
    image: php:apache  # Utilizamos la imagen de PHP con servidor Apache.
    container_name: PHP-Apache # Asignamos un nombre al contenedor 
    build: 
      context: .
      dockerfile: Dockerfile # Especificamos el contexto y el archivo Dockerfile
    volumes:  # Definimos los volumenes adicionales
      - ./www:/var/www/html:rw # Monta el directorio local "./www" en el directorio "/var/www/html" del contenedor con permisos de lectura y escritura.
    ports:
      - 80:80 # Se Establece conexion el puerto 80 del host al puerto 80 del contenedor.
    depends_on:
      - mysql  # Indicamos que este servicio depende del servicio "mysql".
    networks:
      - redelindio # Asignamos este servicio a la red "redelindio".

  # MySQL  (OK)
  mysql:
    image: mysql  #Utilizamos la imagen mysql
    restart: always # # Indicamos que el contenedor se reinicie automáticamente siempre que se detenga.
     # Configuración de las variables de enotrno
    environment:
      MYSQL_ROOT_PASSWORD: admin123  #Establecemos la contraseña de root para MySQL.
      MYSQL_DATABASE: elindio # Creamos una base de datos llamada elindio
      MYSQL_USER: admin # Creamos una usuario llamado admin
      MYSQL_PASSWORD: admin123 # Establecemos la contraseña al usuario 
    ports:
      - "3306:3306" # Se establece una conexion al puerto 3306 del host al puerto 3306 del contenedor
    volumes: # Definimos volumenes adicionales
      - ./mysql:/docker-entrypoint-initdb.d:rw # Montamos el directorio local "./mysql" en el directorio "/docker-entrypoint-initdb.d" del contenedor con permisos de lectura y escritura.
    networks:
      - redelindio # Asignamos este servicio a la red "redelindio".

  # PHPMyAdmin (OK)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Utilizamos la imagen de PHPMyAdmin.
    links: 
      - mysql   # Indicamos que este servicio se vincule al servicio "Mysql"
    ports:
      - "90:80" # Se establece conexion el puerto 90 del host al puerto 80 del contenedor.
      # Configuración de las variables de enotrno
    environment:
      PMA_HOST: mysql  # Especificamos el host donde se encuentra el servidor MySQL al que PHPMyAdmin se conectará.
      PMA_PORT: 3306  # # Especificamos el puerto del servidor MySQL al que PHPMyAdmin se conectará.
      MYSQL_ROOT_PASSWORD: admin123 # # Establecemos la contraseña de root para MySQL.
    volumes: # Definimos los volumes adicionales
      - './mysql:/containerPath:ro' # Montamos el directorio local "./mysql" en el directorio "/docker-entrypoint-initdb.d" del contenedor con permisos de lectura y escritura.
    networks:
      - redelindio # Asignamos este servicio a la red "redelindio".

  # Portainer (Administrador de Servicios) (OK)
  portainer:
    image: portainer/portainer-ce:latest  # Utiliza la imagen de Portainer la màs reciente
    container_name: portainer # Asignamos un nombre al contenedor.
    restart: always # Indicamos que el contenedor se reinicie automáticamente siempre que se detenga.
    ports:
      - "9000:9000"
    # Se establece conexion el puerto 9000 del host al puerto 9000 del contenedor.
    environment:
      - ADMIN_USERNAME=admin 
      - ADMIN_PASSWORD=administrador 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
      - "portainer_data:/data"
    networks: 
      - redelindio # Asignamos este servicio a la red "redelindio".

networks: 
  redelindio: #Se define la red “redelindio”.
    driver: bridge #Se usa el controlador bridge

volumes: # Se definen los volúmenes 
  openldap-data: #Se define el volumen “openldap-data” 
  portainer_data: #Se define el volumen “portainer_data”